### PR TITLE
Bugfix for SteamOS main branch and a couple of additional features

### PR DESCRIPTION
**Pull request by RodoMa92**
The call regarding get devices has changed on Bluez 5.66. This fixes it. I've also added a couple of icons for keyboard and mouse peripherals.

### CODE REVIEW

**Comment by Outpox** [comment]
Thanks for the PR, I'm currently on vacation and will have a look in the next few days.  
From what I've already seen it looks good.

**Comment by Outpox** [comment]
Finally took the time to review the code and gave it a try. Looks good to me!  
If you're done with the PR I'll merge it and release it.

**Comment by RodoMa92** [comment]
Yes, go ahead,  I'm done with it :P

**Comment by Outpox** [comment]
Awesome, thanks again!

**Comment by Outpox** [comment]
[Release PR](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/404)

**Pull request merged**
